#!/usr/bin/env python2

import argparse

parser = argparse.ArgumentParser(description='Display/Modify EFI NVAR store')
parser.add_argument('file', help='FFS image file extracted with MMTool or EFITool')
args = parser.parse_args()

import struct
from uuid import UUID

class NVarAttr(object):
	BITS = ('Runtime', 'AsciiName', 'LocalGUID', 'DataOnly', 'ExtendedHeader', 'HardwareError', 'AuthWrite', 'Valid')

	@property
	def valid(self):
		return bool(self.value & 0x80)

	@property
	def ascii_name(self):
		return bool(self.value & 0x02)

	@property
	def has_local_guid(self):
		return bool(self.value & 0x04)

	@property
	def data_only(self):
		return bool(self.value & 0x08)

	def __init__(self, value):
		self.value = value

	def __repr__(self):
		r = []
		for idx, name in enumerate(NVarAttr.BITS):
			if self.value & (1 << idx):
				r.append(name)
		return '|'.join(r)

class Store(object):
	def __init__(self, path):
		with open(path, 'rb') as f:
			data = f.read()

		guid = UUID(bytes_le = data[0:16])
		checksum, type, attrs, size = struct.unpack('<HBBI', data[16:24])
		state = size >> 24
		size &= 0xffffff
		print "checksum 0x%04x, type 0x%02x, attrs 0x%02x, size: 0x%04x, state: 0x%02x" %(checksum, type, attrs, size, state)
		self.data = data
		self.body = data[24:]
		if len(self.data) != size:
			raise Exception("invalid size in header")

		self.__parse()

	def __guid(self, idx):
		return UUID(bytes_le = self.data[idx: idx + 16])

	def __get_guid(self, idx):
		size = len(self.data)
		idx = size - (idx + 1) * 16
		return self.__guid(idx)

	def __parse(self):
		offset = 24
		data = self.data
		while offset < len(data):
			magic, size, next_offset = struct.unpack('<IHI', data[offset:offset + 10])
			if magic == 0xffffffff: #free space
				break
			if magic != 0x5241564e: #'NVAR'
				raise Exception('invalid NVAR signature at 0x%04x' %offset)

			attr = NVarAttr(next_offset >> 24)
			print "%04x: %5d next: 0x%04x %s" %(offset, size, next_offset, attr)

			_offset = offset
			_next_offset = offset + size
			offset += 10

			if not attr.valid:
				offset = _next_offset
				continue

			if not attr.data_only:
				if attr.has_local_guid:
					print 'GUID', self.__guid(offset)
					offset += 16
				else:
					guid_index = ord(data[offset])
					print 'GUID', self.__get_guid(guid_index), guid_index
					offset += 1

				if attr.ascii_name:
					zero = data.index('\x00', offset)
					if zero >= offset + size:
						raise Exception('invalid ascii name')
					name = data[offset: zero]
					print 'NAME', name
				else:
					zero = data.index('\x00\x00', offset)
					if zero >= offset + size:
						raise Exception('invalid ucs name')
					name = str(data[offset: zero]).decode('utf16')
					print 'NAME', name
			else: #data only
				print 'DATA ONLY'

			next_offset &= 0xffffff
			if next_offset != 0xffffff:
				_next_offset = _offset + next_offset
			offset = _next_offset

store = Store(args.file)
